# https://docs.github.com/en/actions

name: "Release"

on: # yamllint disable-line rule:true
  push:
    tags:
      - "**"

jobs:
  release:
    name: SpringBoot Native Application on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3

      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.1'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
#      - name: Download Maven
#        run: |
#          curl -sL https://www-eu.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.zip -o maven.zip
#          apt-get update
#          apt-get -y install unzip
#          unzip -d /usr/share maven.zip
#          rm maven.zip
#          ln -s /usr/share/apache-maven-3.6.3/bin/mvn /usr/bin/mvn
#          echo "M2_HOME=/usr/share/apache-maven-3.6.3" | tee -a /etc/environment
      - name: Build with Maven
        run: mvn --batch-mode -Pnative native:compile

      - name: "Create release"
        uses: "ergebnis/.github/actions/github/release/create@1.8.0"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Release artifacts
        uses: softprops/action-gh-release@v1
        with:
          draft: false # Remove this to publish the release once tested and confirmed.
          files: | # Update this path to match your artifacts location.
            ./target/sb3-native-image-${{ matrix.os }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}